project:
  name: "bank-client-subscription-classifier"
  description: "Kaggle Playground Series S5E8 - Bank Client Subscription Prediction"
  author: "Álvaro Granados"

data:
  raw_data_path: "data/raw/"
  processed_data_path: "data/processed/"
  train_file: "train.csv"
  test_file: "test.csv"
  target_column: "y"
  id_column: "id"

features:
  categorical_features:
    [job, marital, education, default, housing, loan, contact, month, poutcome]
  numerical_features: [age, balance, day, duration, campaign, pdays, previous]
  features_to_drop: [id]
  unknown_values: ["unknown"]

model:
  random_state: 42
  test_size: 0.2
  cv_folds: 5

mlflow:
  experiment_name: "bank-subscription-prediction"
  tracking_uri: "sqlite:///mlflow.db"
  artifact_location: "./mlartifacts"

hyperparameters:
  lightgbm:
    n_estimators: 200
    learning_rate: 0.1
    max_depth: 3
    num_leaves: 50
    min_child_samples: 30

  xgboost:
    n_estimators: 200
    learning_rate: 0.1
    max_depth: 7
    min_child_weight: 4

  catboost:
    iterations: 200
    learning_rate: 0.1
    depth: 8
    l2_leaf_reg: 4
